all: main.tex ref.bib
	xelatex -synctex=1 -interaction=nonstopmode main.tex
	xelatex -synctex=1 -interaction=nonstopmode main.tex
	bibtex main.aux
	xelatex -synctex=1 -interaction=nonstopmode main.tex
	xelatex -synctex=1 -interaction=nonstopmode main.tex

clean:
	rm -rf *.aux
	rm -rf *.lof
	rm -rf *.log
	rm -rf *.lot
	rm -rf *.fls
	rm -rf *.out
	rm -rf *.toc
	rm -rf *.fmt
	rm -rf *.fot
	rm -rf *.cb
	rm -rf *.cb2
	rm -rf .*.lb
	rm -rf *.dvi
	rm -rf *.xdv
	rm -rf *-converted-to.*
	rm -rf *.bcf
	rm -rf *.blg
	rm -rf *-blx.aux
	rm -rf *-blx.bib
	rm -rf *.run.xml
	rm -rf *.fdb_latexmk
	rm -rf *.synctex
	rm -rf *.synctex.gz
	rm -rf *.pdfsync
	rm -rf latex.out/
	rm -rf *.alg
	rm -rf *.loa
	rm -rf acs-*.bib
	rm -rf *.thm
	rm -rf *.nav
	rm -rf *.pre
	rm -rf *.snm
	rm -rf *.vrb
	rm -rf *.soc
	rm -rf *.cut
	rm -rf *.cpt
	rm -rf *.spl
	rm -rf *.ent
	rm -rf *.lox
	rm -rf *.mf
	rm -rf *.mp
	rm -rf *.tfm
	rm -rf *.end
	rm -rf *.?end
	rm -rf *.acn
	rm -rf *.acr
	rm -rf *.glg
	rm -rf *.glo
	rm -rf *.gls
	rm -rf *.glsdefs
	rm -rf *.lzo
	rm -rf *.lzs
	rm -rf *.slg
	rm -rf *.slo
	rm -rf *.sls
	rm -rf *.gnuplot
	rm -rf *.table
	rm -rf *-gnuplottex-*
	rm -rf *.gaux
	rm -rf *.glog
	rm -rf *.gtex
	rm -rf *.4ct
	rm -rf *.4tc
	rm -rf *.idv
	rm -rf *.lg
	rm -rf *.trc
	rm -rf *.xref
	rm -rf *.brf
	rm -rf *-concordance.tex
	rm -rf *-tikzDictionary
	rm -rf *.lol
	rm -rf *.ltjruby
	rm -rf *.idx
	rm -rf *.ilg
	rm -rf *.ind
	rm -rf *.maf
	rm -rf *.mlf
	rm -rf *.mlt
	rm -rf _minted*
	rm -rf *.pyg
	rm -rf *.mw
	rm -rf *.newpax
	rm -rf *.nlg
	rm -rf *.nlo
	rm -rf *.nls
	rm -rf *.pax
	rm -rf *.pdfpc
	rm -rf *.sagetex.sage
	rm -rf *.sagetex.py
	rm -rf *.sagetex.scmd
	rm -rf *.wrt
	rm -rf svg-inkscape/
	rm -rf *.sout
	rm -rf *.sympy
	rm -rf sympy-plots-for-*.tex/
	rm -rf *.upa
	rm -rf *.upb
	rm -rf *.pytxcode
	rm -rf pythontex-files-*/
	rm -rf *.listing
	rm -rf *.loe
	rm -rf *.dpth
	rm -rf *.md5
	rm -rf *.auxlock
	rm -rf *.ptc
	rm -rf *.tdo
	rm -rf *.hst
	rm -rf *.ver
	rm -rf *.lod
	rm -rf *.xcp
	rm -rf *.xmpi
	rm -rf *.xdy
	rm -rf *.xyc
	rm -rf *.xdy
	rm -rf *.ttt
	rm -rf *.fff
	rm -rf TSWLatexianTemp*
	rm -rf *.bak
	rm -rf *.sav
	rm -rf .texpadtmp
	rm -rf *.lyx~
	rm -rf *.backup
	rm -rf .*.swp
	rm -rf *.tps
	rm -rf ./auto/*
	rm -rf *.el
	rm -rf *-tags.tex
	rm -rf *.sta
	rm -rf *.lpz
	rm -rf *.xwm
	rm -rf *.bbl
	rm -rf *.synctex*
	rm -rf *.toc
	rm -rf *.toe